name: SonarQube Frontend Analysis

on:
  push:
    branches: [ main, dev, production ]
  pull_request:
    branches: [ production, dev, test ]
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend-react/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend-react
        run: npm ci

      - name: Run frontend tests with coverage
        run: npm test -- --coverage --watchAll=false --ci

      - name: Create sonar properties
        run: |
          cat > sonar-project.properties << 'EOL'
          sonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          sonar.projectName=LMS Frontend
          sonar.sources=src
          sonar.tests=src/__tests__

          sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.tsx,**/tests/**,**/coverage/**
          sonar.test.inclusions=**/*.test.js,**/*.test.tsx
          sonar.javascript.lcov.reportPaths=coverage/lcov.info
          sonar.sourceEncoding=UTF-8
          EOL

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
